baseURL = "https://bellerophon95.github.io/mypage/"
title = "Vibhor Kashmira"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 6
enableEmoji = true

contentDir = "content"

[params]
author = "Vibhor Kashmira"
description = "Vibhor Kashmira is a Fullstack Software Engineer specializing in event-driven backend systems, data-intensive applications, and frontend performance optimization."
keywords = "Vibhor Kashmira, Fullstack Engineer, Backend Developer, Applied AI Engineer, AWS EKS, Kafka, GraphQL, Spring Boot, React"
info = ["Innovative software engineer with well-rounded cross-stack expertise. Specializing in frontend performance optimization, event-driven backend systems and data-intensive applications."]
avatarURL = "images/bevis.png"
dateFormat = "January 2, 2006"
since = 2019
commit = "https://github.com/luizdepra/hugo-coder/tree/"
rtl = false
colorScheme = "dark"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = []
customSCSS = ["scss/custom.scss"]
customJS = []

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/bellerophon95"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/vibhor-kashmira-1b875689/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Project Nexus"
weight = 1
url = "nexus/"

[[languages.en.menu.main]]
name = "Project Rentaroost"
weight = 2
url = "rentaroost/"

[[languages.en.menu.main]]
name = "Resume"
weight = 3
url = "docs/vibhor_kashmira_resume.pdf"

[[languages.en.menu.main]]
name = "Contact"
weight = 4
url = "contact/"

[taxonomies]
tag = ""
category = ""
series = ""

[sitemap]
changefreq = "monthly"
priority = 0.5

disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[markup.highlight]
noClasses = false
